services:
  ao-analytics-migrator:
    container_name: ao-analytics-migrator
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    restart: no
    depends_on:
      - ao-analytics-db
